#!/usr/bin/env python3
# encoding: utf-8 (as per PEP 263)

import sys
import re

def timetomin(t):
    parts = t.split(':')
    return 60*int(parts[0]) + int(parts[1])

def mintotime(m):
    return '%01d:%02d' % (m//60, m%60)

def timediff(t1, t2):
    t1 = timetomin(t1)
    t2 = timetomin(t2)
    if t2 > t1:
        # same day
        d = t2 - t1
    else:
        # past midnight
        d = (24*60 - t1) + t2
    return d


def main():
    line = sys.stdin.readline().strip()

    while line:
        tokens = re.findall('\d{1,2}:\d{2}|\d{1,2}|\.+|-|\+', line)

        dots = [i for i, x in enumerate(tokens) if '.' in str(x)]
        for i in dots:
            tokens[i] = timediff(tokens[i-1], tokens[i+1])
            tokens[i-1] = None
            tokens[i+1] = None

        tokens = [x for x in tokens if x is not None]

        composites = [i for i, x in enumerate(tokens) if ':' in str(x)]
        for i in composites:
            tokens[i] = timetomin(tokens[i])

        sum = 0
        while tokens:
            if tokens[0] not in ['-', '+']:
                sum += int(tokens[0])
            elif tokens[0] == '-':
                sum -= int(tokens[1])
                del tokens[1]
            elif tokens[0] == '+':
                sum += int(tokens[1])
                del tokens[1]
            del tokens[0]

        print(mintotime(sum))

        line = sys.stdin.readline().strip()

if __name__ == '__main__':
    main()
