#!/usr/bin/env python3
# encoding: utf-8 (as per PEP 263)

import sys
import re

def timetomin(t):
    parts = t.split(':')
    return 60*int(parts[0]) + int(parts[1])

def mintotime(m):
    return '%01d:%02d' % (m//60, m%60)

def timediff(t1, t2):
    t1 = timetomin(t1)
    t2 = timetomin(t2)
    if t2 > t1:
        # same day
        d = t2 - t1
    else:
        # past midnight
        d = (24*60 - t1) + t2
    return d


def main():
    line = sys.stdin.readline().strip()

    while line:
        verbose = line.endswith('?')

        tokens = re.findall('\d{1,2}:\d{2}|\d{1,2}|\.+|-|\+', line)

        dots = [i for i, x in enumerate(tokens) if '.' in str(x)]
        for i in dots:
            tokens[i] = timediff(tokens[i-1], tokens[i+1])
            if verbose:
                print('. %s to %s = %d minutes (%s)' % (tokens[i-1], tokens[i+1], tokens[i], mintotime(tokens[i])))
            tokens[i-1] = None
            tokens[i+1] = None

        tokens = [x for x in tokens if x is not None]

        composites = [i for i, x in enumerate(tokens) if ':' in str(x)]
        for i in composites:
            t = timetomin(tokens[i])
            if verbose:
                print('> %s = %d minutes (%s)' % (tokens[i], t, mintotime(t)))
            tokens[i] = t

        sum = 0
        while tokens:
            if tokens[0] not in ['-', '+']:
                tokens[0] = int(tokens[0])
                sum += tokens[0]
                if verbose:
                    print('< %d minutes = %d total (%s)' % (tokens[0], sum, mintotime(sum)))
            elif tokens[0] == '-':
                tokens[1] = int(tokens[1])
                sum -= tokens[1]
                if verbose:
                    print('- %d minutes = %d total (%s)' % (tokens[1], sum, mintotime(sum)))
                del tokens[1]
            elif tokens[0] == '+':
                tokens[1] = int(tokens[1])
                sum += tokens[1]
                if verbose:
                    print('+ %d minutes = %d total (%s)' % (tokens[1], sum, mintotime(sum)))
                del tokens[1]
            del tokens[0]

        print(mintotime(sum))

        line = sys.stdin.readline().strip()

if __name__ == '__main__':
    main()
